# Generated by Django 4.2.1 on 2023-10-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 10, 16, 10, 6, 382361, tzinfo=datetime.timezone.utc)),
        ),
    ]
