# Generated by Django 4.2.2 on 2023-10-15 06:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminTruckNumber', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('docketGiven', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10-digit number without any special characters or spaces.', regex='^\\d{10}$')])),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NatureOfLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.natureofleave')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTruckConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientTruckId', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('startDate', models.DateField(default=datetime.datetime(2023, 10, 15, 6, 46, 3, 254748, tzinfo=datetime.timezone.utc))),
                ('endDate', models.DateField(blank=True, null=True)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.client')),
                ('truckNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.admintruck')),
            ],
        ),
    ]
