# Generated by Django 4.2.2 on 2023-10-12 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0002_alter_clienttruckconnection_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 16, 3, 13, 571991, tzinfo=datetime.timezone.utc)),
        ),
    ]
