# Generated by Django 4.2.1 on 2023-10-20 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0002_alter_clienttruckconnection_clienttruckid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttruckconnection',
            name='truckType',
            field=models.CharField(default='Embedded', max_length=254),
        ),
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 12, 23, 44, 735004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2033, 10, 7, 12, 23, 44, 732011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 12, 23, 44, 732011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2033, 10, 7, 12, 23, 44, 734017, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 12, 23, 44, 734017, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2033, 10, 7, 12, 23, 44, 732011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 12, 23, 44, 732011, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2033, 10, 7, 12, 23, 44, 733009, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 12, 23, 44, 733009, tzinfo=datetime.timezone.utc)),
        ),
    ]
