# Generated by Django 4.2.2 on 2023-10-13 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0004_alter_clienttruckconnection_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 13, 5, 8, 23, 847047, tzinfo=datetime.timezone.utc)),
        ),
    ]
