# Generated by Django 5.0.1 on 2024-02-10 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0005_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckinformation',
            old_name='customFuelCard',
            new_name='customFieldLabel1',
        ),
        migrations.RenameField(
            model_name='truckinformation',
            old_name='customFuelOldFleetNumber',
            new_name='customFieldLabel2',
        ),
        migrations.RenameField(
            model_name='truckinformation',
            old_name='customOldRego',
            new_name='customFieldLabel3',
        ),
        migrations.RenameField(
            model_name='truckinformation',
            old_name='customPDDNumber',
            new_name='customFieldLabel4',
        ),
        migrations.RenameField(
            model_name='truckinformation',
            old_name='customRegisteredOwner',
            new_name='customFieldLabel5',
        ),
        migrations.RenameField(
            model_name='truckinformation',
            old_name='customRoadsideAssistance',
            new_name='customFieldLabel6',
        ),
        migrations.RenameField(
            model_name='truckinformation',
            old_name='registrationSate',
            new_name='customFieldValue1',
        ),
        migrations.AddField(
            model_name='truckinformation',
            name='customFieldValue2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckinformation',
            name='customFieldValue3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckinformation',
            name='customFieldValue4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckinformation',
            name='customFieldValue5',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckinformation',
            name='customFieldValue6',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckinformation',
            name='registrationState',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 5, 33, 41, 910615, tzinfo=datetime.timezone.utc)),
        ),
    ]
