# Generated by Django 5.0.1 on 2024-02-10 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0008_clienttruckconnection_baseplantid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckinformationcustom',
            old_name='customFieldLabel1',
            new_name='customFieldLabel',
        ),
        migrations.RemoveField(
            model_name='truckinformationcustom',
            name='customFieldLabel2',
        ),
        migrations.RemoveField(
            model_name='truckinformationcustom',
            name='customFieldLabel3',
        ),
        migrations.RemoveField(
            model_name='truckinformationcustom',
            name='customFieldLabel4',
        ),
        migrations.RemoveField(
            model_name='truckinformationcustom',
            name='customFieldLabel5',
        ),
        migrations.RemoveField(
            model_name='truckinformationcustom',
            name='customFieldLabel6',
        ),
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 9, 34, 17, 914884, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 9, 34, 17, 906913, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 9, 34, 17, 906913, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 9, 34, 17, 909882, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 9, 34, 17, 909882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 9, 34, 17, 910923, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 9, 34, 17, 910923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 9, 34, 17, 907882, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 9, 34, 17, 907882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 9, 34, 17, 907882, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 9, 34, 17, 907882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 9, 34, 17, 908900, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 9, 34, 17, 908900, tzinfo=datetime.timezone.utc)),
        ),
    ]
