# Generated by Django 4.2.2 on 2024-02-09 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0008_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_axle1', models.IntegerField(choices=[(0, 'None'), (1, 'Single'), (2, 'Dual'), (3, 'Triple'), (4, 'Quad')], default=0)),
                ('vehicle_axle2', models.IntegerField(choices=[(0, 'None'), (1, 'Single'), (2, 'Dual'), (3, 'Triple'), (4, 'Quad')], default=0)),
                ('vehicle_axle3', models.IntegerField(choices=[(0, 'None'), (1, 'Single'), (2, 'Dual'), (3, 'Triple'), (4, 'Quad')], default=0)),
                ('vehicle_axle4', models.IntegerField(choices=[(0, 'None'), (1, 'Single'), (2, 'Dual'), (3, 'Triple'), (4, 'Quad')], default=0)),
                ('vehicle_axle5', models.IntegerField(choices=[(0, 'None'), (1, 'Single'), (2, 'Dual'), (3, 'Triple'), (4, 'Quad')], default=0)),
                ('vehicle_axle6', models.IntegerField(choices=[(0, 'None'), (1, 'Single'), (2, 'Dual'), (3, 'Triple'), (4, 'Quad')], default=0)),
                ('vehicle_axle7', models.IntegerField(choices=[(0, 'None'), (1, 'Single'), (2, 'Dual'), (3, 'Triple'), (4, 'Quad')], default=0)),
                ('vehicle_axle8', models.IntegerField(choices=[(0, 'None'), (1, 'Single'), (2, 'Dual'), (3, 'Triple'), (4, 'Quad')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TruckGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='admintruck',
            old_name='truckStatus',
            new_name='truckActive',
        ),
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 6, 52, 13, 851152, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 6, 6, 52, 13, 845146, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 6, 52, 13, 845146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 6, 6, 52, 13, 848146, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 6, 52, 13, 848146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 6, 6, 52, 13, 849146, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 6, 52, 13, 849146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 6, 6, 52, 13, 846146, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 6, 52, 13, 846146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 6, 6, 52, 13, 846146, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 6, 52, 13, 846146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 6, 6, 52, 13, 848146, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 6, 52, 13, 847147, tzinfo=datetime.timezone.utc)),
        ),
    ]
