# Generated by Django 5.0.1 on 2024-02-10 12:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0009_rename_customfieldlabel1_truckinformationcustom_customfieldlabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 7, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 12, 48, 52, 49752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='clientOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationType', models.CharField(choices=[('Home', 'Home'), ('Workplace', 'Workplace')], max_length=10)),
                ('description', models.CharField(default='', max_length=2048, null=True)),
                ('address1', models.CharField(default='', max_length=1024, null=True)),
                ('address2', models.CharField(default='', max_length=1024, null=True)),
                ('personName', models.CharField(default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100, null=True)),
                ('state', models.CharField(default='', max_length=100, null=True)),
                ('country', models.CharField(default='', max_length=100, null=True)),
                ('postalCode', models.IntegerField(default=0, null=True)),
                ('primaryContact', models.IntegerField(default=0, null=True)),
                ('alternativeContact', models.IntegerField(default=0, null=True)),
                ('clientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.client')),
            ],
        ),
    ]
