# Generated by Django 5.0.1 on 2024-02-18 13:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0014_rename_waiting_grace_per_cubic_meter_grace_minimum_load_size_for_waiting_time_grace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelType', models.CharField(max_length=100)),
                ('fuelCreditCategory', models.CharField(max_length=100)),
                ('adbluePercent', models.FloatField(blank=True, null=True)),
                ('kilometersOffset', models.FloatField(blank=True, null=True)),
                ('hoursOffset', models.FloatField(blank=True, null=True)),
                ('preStartChecklist', models.CharField(max_length=100)),
                ('trailers', models.CharField(max_length=100)),
                ('GCM', models.FloatField(blank=True, null=True)),
                ('GVM', models.FloatField(blank=True, null=True)),
                ('TARE', models.FloatField(blank=True, null=True)),
                ('ATM', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('pallets', models.FloatField(blank=True, null=True)),
                ('customText1', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue1', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText2', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue2', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText3', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue3', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText4', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue4', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText5', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue5', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText6', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue6', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText7', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue7', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText8', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue8', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText9', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue9', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText10', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue10', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText11', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue11', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText12', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue12', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText13', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue13', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText14', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue14', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText15', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue15', models.CharField(blank=True, max_length=2048, null=True)),
                ('customText16', models.CharField(blank=True, max_length=1024, null=True)),
                ('customValue16', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckSettingCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customFieldLabel', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='clienttruckconnection',
            name='basePlantId',
        ),
        migrations.AddField(
            model_name='clienttruckconnection',
            name='clientOfc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.clientoffice'),
        ),
        migrations.AddField(
            model_name='clienttruckconnection',
            name='neverEnding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 13, 34, 50, 652019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 15, 13, 34, 50, 641021, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 13, 34, 50, 641021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 15, 13, 34, 50, 644018, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 13, 34, 50, 644018, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 15, 13, 34, 50, 645019, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 13, 34, 50, 645019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 15, 13, 34, 50, 641021, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 13, 34, 50, 641021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 15, 13, 34, 50, 642020, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 13, 34, 50, 642020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 15, 13, 34, 50, 643020, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 13, 34, 50, 643020, tzinfo=datetime.timezone.utc)),
        ),
    ]
