# Generated by Django 5.0.1 on 2024-02-21 07:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0020_clienttruckconnection_neverending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttruckconnection',
            name='clientOfc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.clientoffice'),
        ),
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 52, 55, 437380, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='truckNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.admintruck'),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 18, 7, 52, 55, 425381, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 52, 55, 425381, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 18, 7, 52, 55, 429380, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 52, 55, 428380, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 18, 7, 52, 55, 429380, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 52, 55, 429380, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 18, 7, 52, 55, 426382, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 52, 55, 426382, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 18, 7, 52, 55, 427381, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 52, 55, 427381, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 2, 18, 7, 52, 55, 428380, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 7, 52, 55, 428380, tzinfo=datetime.timezone.utc)),
        ),
    ]
