# Generated by Django 5.0.1 on 2024-03-09 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0030_alter_clienttruckconnection_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 552774)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='historicalclienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 552774)),
        ),
        migrations.AlterField(
            model_name='historicalcostparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='historicalcostparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='historicalgrace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='historicalgrace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='historicalonlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='historicalonlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='historicalratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='historicalratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='historicalthresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='historicalthresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='historicalthresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='historicalthresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 7, 21, 59, 27, 521524), null=True),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 59, 27, 521524)),
        ),
    ]
