# Generated by Django 5.0.1 on 2024-03-21 15:44

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0031_alter_clienttruckconnection_startdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 288327)),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 257052), null=True),
        ),
        migrations.AlterField(
            model_name='costparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 257052)),
        ),
        migrations.AlterField(
            model_name='grace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 272677), null=True),
        ),
        migrations.AlterField(
            model_name='grace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 272677)),
        ),
        migrations.AlterField(
            model_name='historicalclienttruckconnection',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 288327)),
        ),
        migrations.AlterField(
            model_name='historicalcostparameters',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 257052), null=True),
        ),
        migrations.AlterField(
            model_name='historicalcostparameters',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 257052)),
        ),
        migrations.AlterField(
            model_name='historicalgrace',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 272677), null=True),
        ),
        migrations.AlterField(
            model_name='historicalgrace',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 272677)),
        ),
        migrations.AlterField(
            model_name='historicalonlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 272677), null=True),
        ),
        migrations.AlterField(
            model_name='historicalonlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 272677)),
        ),
        migrations.AlterField(
            model_name='historicalratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 257052), null=True),
        ),
        migrations.AlterField(
            model_name='historicalratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 257052)),
        ),
        migrations.AlterField(
            model_name='historicalthresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 257052), null=True),
        ),
        migrations.AlterField(
            model_name='historicalthresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 257052)),
        ),
        migrations.AlterField(
            model_name='historicalthresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 257052), null=True),
        ),
        migrations.AlterField(
            model_name='historicalthresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 257052)),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 272677), null=True),
        ),
        migrations.AlterField(
            model_name='onlease',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 272677)),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 257052), null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsurchargevalue',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 257052)),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 257052), null=True),
        ),
        migrations.AlterField(
            model_name='thresholddayshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 257052)),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2034, 3, 19, 15, 44, 46, 257052), null=True),
        ),
        migrations.AlterField(
            model_name='thresholdnightshift',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 15, 44, 46, 257052)),
        ),
        migrations.CreateModel(
            name='HistoricalTruckToll',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tollDate', models.DateField(null=True)),
                ('tollAmount', models.FloatField(default=0, null=True)),
                ('comment', models.CharField(default='', max_length=2048, null=True)),
                ('tollImage', models.TextField(max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('truckNo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='GearBox_app.clienttruckconnection')),
            ],
            options={
                'verbose_name': 'historical truck toll',
                'verbose_name_plural': 'historical truck tolls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TruckToll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tollDate', models.DateField(null=True)),
                ('tollAmount', models.FloatField(default=0, null=True)),
                ('comment', models.CharField(default='', max_length=2048, null=True)),
                ('tollImage', models.FileField(null=True, upload_to='static/GearBox/toll')),
                ('truckNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.clienttruckconnection')),
            ],
        ),
    ]
