# Generated by Django 4.2.2 on 2024-02-03 13:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GearBox_app', '0002_alter_clienttruckconnection_startdate_and_more'),
        ('Account_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Dispatched', 'Dispatched'), ('InProgress', 'InProgress'), ('Incomplete', 'Incomplete'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='incomplete', max_length=20)),
                ('staffNotes', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('shiftType', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=10)),
                ('createdTime', models.TimeField(blank=True, default=datetime.datetime(2024, 2, 3, 13, 33, 50, 631318, tzinfo=datetime.timezone.utc), null=True)),
                ('preStartWindow', models.CharField(default='15', max_length=2)),
                ('startTime', models.TimeField(blank=True, default=None, null=True)),
                ('endTime', models.TimeField(blank=True, default=None, null=True)),
                ('reportingTime', models.TimeField(blank=True, default=None, null=True)),
                ('startDate', models.DateField(blank=True, default=None, null=True)),
                ('endDate', models.DateField(blank=True, default=None, null=True)),
                ('recurringType', models.CharField(choices=[('NoRecurring', 'NoRecurring'), ('Daily', 'Daily'), ('Custom', 'Custom')], default='NoRecurring', max_length=20)),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_app.baseplant')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPreStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curDateTime', models.DateTimeField(default=None, null=True)),
                ('comment', models.CharField(default='', max_length=2048, null=True)),
                ('clientId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.client')),
                ('driverId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='PreStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preStartName', models.CharField(default='', max_length=50, null=True)),
                ('createdDate', models.DateTimeField(default=None, null=True)),
                ('createdBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreStartQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(default='', max_length=1024, null=True)),
                ('questionType', models.CharField(choices=[('Vehicle related', 'Vehicle related'), ('Driver related', 'Driver related'), ('Other', 'Other')], max_length=20)),
                ('optionTxt1', models.CharField(default='', max_length=30, null=True)),
                ('wantFile1', models.BooleanField(default=False)),
                ('optionTxt2', models.CharField(blank=True, max_length=30, null=True)),
                ('wantFile2', models.BooleanField(default=False)),
                ('optionTxt3', models.CharField(blank=True, max_length=30, null=True)),
                ('wantFile3', models.BooleanField(default=False)),
                ('optionTxt4', models.CharField(blank=True, max_length=30, null=True)),
                ('wantFile4', models.BooleanField(default=False)),
                ('preStartId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.prestart')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPreStartQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=255, null=True)),
                ('answerFile', models.FileField(default=None, null=True, upload_to='')),
                ('comment', models.CharField(default='', max_length=2048, null=True)),
                ('preStartId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.driverprestart')),
                ('questionId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.prestartquestion')),
            ],
        ),
        migrations.AddField(
            model_name='driverprestart',
            name='preStartId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.prestart'),
        ),
        migrations.AddField(
            model_name='driverprestart',
            name='shiftId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershift'),
        ),
        migrations.AddField(
            model_name='driverprestart',
            name='tripId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershifttrip'),
        ),
        migrations.AddField(
            model_name='driverprestart',
            name='truckConnectionId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.clienttruckconnection'),
        ),
        migrations.CreateModel(
            name='AppointmentTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.appointment')),
                ('truckNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.admintruck')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.appointment')),
                ('driverName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver')),
            ],
        ),
    ]
