# Generated by Django 4.2.2 on 2024-02-07 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0009_alter_driverdocket_shiftdate'),
        ('Appointment_app', '0002_alter_appointment_createdtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='driverNotes',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 2, 7, 12, 6, 49, 910812, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account_app.baseplant'),
        ),
        migrations.CreateModel(
            name='AppointmentStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.appointment')),
                ('stopName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_app.baseplant')),
            ],
        ),
    ]
