# Generated by Django 5.0.1 on 2024-02-07 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0002_alter_appointment_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 2, 7, 11, 19, 46, 211902, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Other', 'Other'), ('Driver related', 'Driver related'), ('Vehicle related', 'Vehicle related')], max_length=20),
        ),
    ]
