# Generated by Django 5.0.1 on 2024-02-12 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0002_appointmentstop_arrivaltime_appointmentstop_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentstop',
            old_name='noted',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 2, 12, 10, 35, 25, 166994, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Driver related', 'Driver related'), ('Other', 'Other'), ('Vehicle related', 'Vehicle related')], max_length=20),
        ),
    ]
