# Generated by Django 5.0.1 on 2024-02-13 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0003_rename_noted_appointmentstop_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 2, 13, 5, 28, 45, 365131, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='driverprestart',
            name='curDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Vehicle related', 'Vehicle related'), ('Driver related', 'Driver related'), ('Other', 'Other')], max_length=20),
        ),
    ]
