# Generated by Django 4.2.2 on 2024-02-08 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0003_appointment_drivernotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 2, 8, 8, 3, 19, 205422, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Other', 'Other'), ('Driver related', 'Driver related'), ('Vehicle related', 'Vehicle related')], max_length=20),
        ),
    ]
