# Generated by Django 5.0.1 on 2024-02-13 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0004_alter_appointment_createdtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 2, 13, 5, 31, 56, 494089, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
