# Generated by Django 4.2.2 on 2024-02-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0003_alter_appointment_createdtime_and_more'),
        ('Appointment_app', '0004_alter_appointment_createdtime_and_more'),
    ]

    operations = [
    ]
