# Generated by Django 4.2.2 on 2024-02-09 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0005_merge_20240208_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 2, 9, 6, 52, 13, 869780, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Vehicle related', 'Vehicle related'), ('Other', 'Other'), ('Driver related', 'Driver related')], max_length=20),
        ),
    ]
