# Generated by Django 5.0.1 on 2024-03-07 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0006_prestartquestion_questionno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestartquestion',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 3, 7, 21, 25, 21, 388820), null=True),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Driver related', 'Driver related'), ('Other', 'Other'), ('Vehicle related', 'Vehicle related')], max_length=20),
        ),
    ]
