# Generated by Django 5.0.1 on 2024-03-08 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0007_prestartquestion_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprestart',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 3, 8, 15, 54, 37, 183456), null=True),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Vehicle related', 'Vehicle related'), ('Driver related', 'Driver related'), ('Other', 'Other')], max_length=20),
        ),
    ]
