# Generated by Django 5.0.1 on 2024-03-08 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0008_driverprestart_archive_alter_appointment_createdtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprestart',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 3, 8, 20, 6, 37, 198383), null=True),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Vehicle related', 'Vehicle related'), ('Other', 'Other'), ('Driver related', 'Driver related')], max_length=20),
        ),
    ]
