# Generated by Django 4.2.2 on 2024-01-16 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0016_alter_clienttruckconnection_startdate_and_more'),
        ('Account_app', '0056_alter_driverdocket_shiftdate'),
        ('Appointment_app', '0011_remove_prestartquestion_optioncomment1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 9, 7, 51, 236541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 7, 51, 236541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 7, 51, 236541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 7, 51, 236541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Other', 'Other'), ('Vehicle related', 'Vehicle related'), ('Driver related', 'Driver related')], max_length=20),
        ),
        migrations.CreateModel(
            name='DriverPreStartQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=255, null=True)),
                ('answerFile', models.FileField(default=None, null=True, upload_to='')),
                ('comment', models.CharField(default='', max_length=2048, null=True)),
                ('preStartId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.prestart')),
                ('questionId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.prestartquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPreStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curDateTime', models.DateTimeField(default=None, null=True)),
                ('comment', models.CharField(default='', max_length=2048, null=True)),
                ('clientId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.client')),
                ('driverId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver')),
                ('preStartId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.prestart')),
                ('shiftId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershift')),
                ('tripId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershifttrip')),
                ('truckConnectionId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.clienttruckconnection')),
            ],
        ),
    ]
