# Generated by Django 4.2.2 on 2024-01-16 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0012_alter_appointment_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 9, 8, 53, 398859, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 8, 53, 397717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 8, 53, 397717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 8, 53, 397717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='driverprestartquestion',
            name='preStartId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment_app.driverprestart'),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Driver related', 'Driver related'), ('Vehicle related', 'Vehicle related'), ('Other', 'Other')], max_length=20),
        ),
    ]
