# Generated by Django 4.2.2 on 2024-01-29 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0013_alter_appointment_created_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Origin',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Created_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='End_Date_Time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Recurring',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Staff_Notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Start_Date_Time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='report_to_origin',
        ),
        migrations.AddField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 1, 29, 12, 47, 28, 240556, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='endTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurringType',
            field=models.CharField(choices=[('NoRecurring', 'NoRecurring'), ('Daily', 'Daily'), ('Custom', 'Custom')], default='Day', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reportingTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staffNotes',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Driver related', 'Driver related'), ('Other', 'Other'), ('Vehicle related', 'Vehicle related')], max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
