# Generated by Django 4.2.2 on 2024-01-29 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0014_rename_created_by_appointment_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createdTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 1, 29, 12, 48, 17, 427379, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recurringType',
            field=models.CharField(choices=[('NoRecurring', 'NoRecurring'), ('Daily', 'Daily'), ('Custom', 'Custom')], default='NoRecurring', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Other', 'Other'), ('Driver related', 'Driver related'), ('Vehicle related', 'Vehicle related')], max_length=20),
        ),
    ]
