# Generated by Django 5.0.1 on 2024-02-01 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_app', '0016_alter_appointment_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Created_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 1, 8, 42, 54, 895437, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='End_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 8, 42, 54, 895437, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 8, 42, 54, 895437, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='report_to_origin',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 8, 42, 54, 895437, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prestartquestion',
            name='questionType',
            field=models.CharField(choices=[('Other', 'Other'), ('Vehicle related', 'Vehicle related'), ('Driver related', 'Driver related')], max_length=20),
        ),
    ]
