# Generated by Django 4.2.1 on 2023-10-20 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 18, 50, 55, 189610, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
