# Generated by Django 4.2.2 on 2024-02-03 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 13, 35, 19, 147577, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
