# Generated by Django 5.0.1 on 2024-02-09 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 8, 51, 13, 315359, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
