# Generated by Django 4.2.2 on 2024-02-04 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0006_alter_clienttruckconnection_startdate_and_more'),
        ('Account_app', '0002_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationdocket',
            name='callOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='callOutCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='cancellationCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='customCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='demurrage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='demurrageCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='returnKm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='returnKmCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='standBy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='standByCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='transferKm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='transferKmCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='truckNo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.clienttruckconnection'),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='waitingTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='waitingTimeCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 12, 46, 45, 407036, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
