# Generated by Django 5.0.1 on 2024-02-10 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0002_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseplant',
            name='basePlantType',
        ),
        migrations.AddField(
            model_name='baseplant',
            name='clientBasePlant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseplant',
            name='clientDepot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 7, 9, 59, 941806, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
