# Generated by Django 5.0.1 on 2024-02-28 13:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0003_remove_baseplant_baseplanttype_and_more'),
        ('GearBox_app', '0025_remove_clientoffice_alternativecontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseplant',
            name='clientOfficeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.clientoffice'),
        ),
        migrations.AddField(
            model_name='baseplant',
            name='depotCode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseplant',
            name='email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 13, 49, 12, 331015, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
