# Generated by Django 5.0.1 on 2024-03-01 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0004_baseplant_clientofficeid_baseplant_depotcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershifttrip',
            name='revenueDeficit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 1, 12, 28, 18, 419719, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
