# Generated by Django 4.2.2 on 2024-02-04 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0004_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationdocket',
            name='blowBack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='blowBackCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='loadKm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='loadKmCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='surcharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalationdocket',
            name='surchargeCharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 17, 7, 56, 901012, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
