# Generated by Django 4.2.2 on 2024-02-04 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0005_escalationdocket_blowback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 17, 9, 1, 610810, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
