# Generated by Django 5.0.1 on 2024-03-02 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0005_drivershifttrip_revenuedeficit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationreport',
            name='driverCancellationCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='driverDemurageCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='rctiCancellatioCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='rctiDemurageCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 2, 4, 16, 27, 718484, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
