# Generated by Django 5.0.1 on 2024-03-04 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0006_reconciliationreport_drivercancellationcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='locationImg',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='endEngineHours',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='endOdometerKms',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='startEngineHours',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='startOdometerKms',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 4, 12, 55, 29, 13733, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
