# Generated by Django 4.2.2 on 2024-02-07 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0006_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 11, 38, 58, 354868, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
