# Generated by Django 5.0.1 on 2024-03-07 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0008_driverbreak_durationinminutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rctiadjustment',
            name='blowBack',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='callOut',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='cancellationCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='demurageCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='loadAndKmCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='loadDeficit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='otherCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='returnKmCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='standByCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='surchargeCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='transferKmCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rctiadjustment',
            name='waitingTimeCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 23, 3, 18, 340413), null=True),
        ),
    ]
