# Generated by Django 5.0.1 on 2024-03-07 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0009_rctiadjustment_blowback_rctiadjustment_callout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rctiadjustment',
            name='loadAndKmCost',
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 23, 28, 59, 779593), null=True),
        ),
    ]
