# Generated by Django 4.2.2 on 2024-02-09 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0009_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 6, 52, 13, 858653, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
