# Generated by Django 5.0.1 on 2024-03-07 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0010_remove_rctiadjustment_loadandkmcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 23, 33, 0, 12253), null=True),
        ),
        migrations.AlterField(
            model_name='rctiadjustment',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rctiadjustment',
            name='docketNumber',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rctiadjustment',
            name='docketYard',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rctiadjustment',
            name='unit',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
