# Generated by Django 5.0.1 on 2024-03-08 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0011_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='endTimeUTC',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='startTimeUTC',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='endTimeUTC',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='startTimeUTC',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 15, 54, 6, 781283), null=True),
        ),
    ]
