# Generated by Django 5.0.1 on 2024-03-09 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0013_drivershift_lastemailtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 21, 58, 55, 162327), null=True),
        ),
    ]
