# Generated by Django 5.0.1 on 2024-03-11 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0014_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='comment',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='endShiftImg',
            field=models.FileField(null=True, upload_to='static/img/shiftImg'),
        ),
        migrations.AddField(
            model_name='historicaldrivershift',
            name='comment',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='historicaldrivershift',
            name='endShiftImg',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 16, 55, 28, 20074), null=True),
        ),
    ]
