# Generated by Django 5.0.1 on 2024-03-12 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0015_drivershift_comment_drivershift_endshiftimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='endLatitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='endLocationImg',
            field=models.FileField(null=True, upload_to='static/Account/driverLocationFiles'),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='endLongitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaldrivershift',
            name='endLatitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaldrivershift',
            name='endLocationImg',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldrivershift',
            name='endLongitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 12, 15, 55, 57, 450111), null=True),
        ),
    ]
