# Generated by Django 5.0.1 on 2024-03-14 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0016_drivershift_endlatitude_drivershift_endlocationimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverreimbursement',
            name='actualAmount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverreimbursement',
            name='status',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldriverreimbursement',
            name='actualAmount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldriverreimbursement',
            name='status',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 14, 15, 29, 25, 292330), null=True),
        ),
    ]
