# Generated by Django 5.0.1 on 2024-03-14 20:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0017_driverreimbursement_actualamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbreak',
            name='nextBreakStartTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='driverbreak',
            name='tripId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershifttrip'),
        ),
        migrations.AddField(
            model_name='driverreimbursement',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='totalBreakInMinute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='totalRunTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldriverbreak',
            name='nextBreakStartTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldriverbreak',
            name='tripId',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Account_app.drivershifttrip'),
        ),
        migrations.AddField(
            model_name='historicaldriverreimbursement',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='historicaldrivershifttrip',
            name='totalBreakInMinute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldrivershifttrip',
            name='totalRunTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverbreak',
            name='endDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='driverbreak',
            name='startDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 14, 20, 56, 27, 236720), null=True),
        ),
        migrations.AlterField(
            model_name='historicaldriverbreak',
            name='endDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldriverbreak',
            name='startDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
