# Generated by Django 5.0.1 on 2024-03-15 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0018_driverbreak_nextbreakstarttime_driverbreak_tripid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivershifttrip',
            name='totalBreakInMinute',
        ),
        migrations.RemoveField(
            model_name='drivershifttrip',
            name='totalRunTime',
        ),
        migrations.RemoveField(
            model_name='historicaldrivershifttrip',
            name='totalBreakInMinute',
        ),
        migrations.RemoveField(
            model_name='historicaldrivershifttrip',
            name='totalRunTime',
        ),
        migrations.AddField(
            model_name='drivershift',
            name='totalBreakInMinute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='totalRunTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldrivershift',
            name='totalBreakInMinute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldrivershift',
            name='totalRunTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 15, 57, 15, 353256), null=True),
        ),
    ]
