# Generated by Django 5.0.1 on 2024-04-10 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0019_remove_drivershifttrip_totalbreakinminute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='chargeJobEditReason',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='drivershiftdocket',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldrivershift',
            name='chargeJobEditReason',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='historicaldrivershiftdocket',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 10, 18, 12, 9, 873627), null=True),
        ),
    ]
