# Generated by Django 5.0.1 on 2024-04-22 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0020_drivershift_chargejobeditreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershifttrip',
            name='basePlant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldrivershifttrip',
            name='basePlant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 22, 15, 6, 27, 438649), null=True),
        ),
    ]
