# Generated by Django 4.2.2 on 2024-01-07 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0042_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 14, 3, 13, 972077, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='escalationType',
            field=models.CharField(choices=[('External', 'External'), ('Internal', 'Internal')], default='External', max_length=20),
        ),
    ]
