# Generated by Django 4.2.2 on 2024-01-08 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0047_escalationmail_mailattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holcimdocket',
            name='additionalKm',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='basePlant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Account_app.baseplant'),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='customerName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='dischargeLocation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='distanceInKm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='materialCode',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='reasonRequested',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='requestedKm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='returnedQty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 12, 44, 22, 14819, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='load',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='waterAdded',
            field=models.FloatField(default=0),
        ),
    ]
