# Generated by Django 4.2.2 on 2024-01-08 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0048_holcimdocket_additionalkm_holcimdocket_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasttriperror',
            name='errorType',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 13, 32, 2, 973022, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
