# Generated by Django 4.2.2 on 2024-01-09 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0049_pasttriperror_errortype_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='holcimdocket',
            name='loadSize',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 15, 23, 8, 800678, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='holcimdocket',
            name='load',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
