# Generated by Django 4.2.2 on 2024-01-09 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0050_holcimdocket_loadsize_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holcimdocket',
            old_name='ticketedDate',
            new_name='docketDate',
        ),
        migrations.AlterUniqueTogether(
            name='holcimdocket',
            unique_together={('jobNo', 'docketDate', 'tripId')},
        ),
        migrations.AddField(
            model_name='holcimdocket',
            name='ticketed',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 15, 33, 48, 480254, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.RemoveField(
            model_name='holcimdocket',
            name='ticketedTime',
        ),
    ]
