# Generated by Django 4.2.2 on 2024-01-12 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0051_rename_ticketeddate_holcimdocket_docketdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('shiftType', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=200)),
                ('shiftDate', models.DateField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('driverId', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverShiftDocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripId', models.PositiveIntegerField(blank=True, null=True)),
                ('docketNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('docketFile', models.FileField(blank=True, null=True, upload_to='static/img/docketFiles')),
                ('basePlant', models.PositiveIntegerField(blank=True, null=True)),
                ('noOfKm', models.FloatField(default=0)),
                ('transferKM', models.FloatField(default=0)),
                ('returnToYard', models.BooleanField(default=False)),
                ('tippingToYard', models.BooleanField(default=False)),
                ('returnQty', models.FloatField(default=0)),
                ('returnKm', models.FloatField(default=0)),
                ('waitingTimeStart', models.TimeField(blank=True, default='', null=True)),
                ('waitingTimeEnd', models.TimeField(blank=True, default='', null=True)),
                ('totalWaitingInMinute', models.FloatField(default=0)),
                ('surchargeType', models.IntegerField(blank=True, null=True)),
                ('surcharge_duration', models.FloatField(default=0)),
                ('cubicMl', models.FloatField(default=0)),
                ('standByStartTime', models.TimeField(blank=True, default='', null=True)),
                ('standByEndTime', models.TimeField(blank=True, default='', null=True)),
                ('standBySlot', models.PositiveIntegerField(default=0, null=True)),
                ('minimumLoad', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
                ('comment', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverShiftTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftId', models.IntegerField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('clientId', models.IntegerField(blank=True, null=True)),
                ('truckConnectionId', models.IntegerField(blank=True, null=True)),
                ('dispute', models.BooleanField(default=False)),
                ('numberOfLoads', models.FloatField(default=0)),
                ('loadSheet', models.FileField(blank=True, null=True, upload_to='static/img/finalloadSheet')),
                ('comment', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 12, 8, 5, 55, 86254, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
