# Generated by Django 4.2.2 on 2024-01-12 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0052_drivershift_drivershiftdocket_drivershifttrip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 12, 9, 29, 32, 792757, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
