# Generated by Django 4.2.1 on 2024-01-16 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0053_drivershift_latitude_drivershift_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationreport',
            name='driverBlowBack',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='driverCallOut',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='rctiBlowBack',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='rctiCallOut',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 3, 16, 25, 924406, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
