# Generated by Django 4.2.2 on 2024-01-17 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0017_alter_clienttruckconnection_startdate_and_more'),
        ('Account_app', '0056_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 4, 38, 2, 266731, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='pasttriperror',
            name='data',
            field=models.CharField(default=' ', max_length=2048),
        ),
        migrations.AlterField(
            model_name='rctierrors',
            name='data',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.CreateModel(
            name='DriverBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default='', null=True)),
                ('endDate', models.DateTimeField(default='', null=True)),
                ('breakFile', models.FileField(default='', null=True, upload_to='')),
                ('location', models.CharField(default='', max_length=2048, null=True)),
                ('description', models.CharField(default='', max_length=2048, null=True)),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver')),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershifttrip')),
            ],
        ),
    ]
