# Generated by Django 4.2.2 on 2024-01-17 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0018_alter_clienttruckconnection_startdate_and_more'),
        ('Account_app', '0057_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverbreak',
            name='tripId',
        ),
        migrations.AddField(
            model_name='driverbreak',
            name='shiftId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershift'),
        ),
        migrations.AlterField(
            model_name='driverbreak',
            name='driverId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver'),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 5, 9, 46, 402976, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
