# Generated by Django 4.2.2 on 2024-01-17 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0058_remove_driverbreak_tripid_driverbreak_shiftid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbreak',
            name='tripId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershifttrip'),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 5, 22, 28, 678684, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
