# Generated by Django 4.2.2 on 2024-01-17 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0059_driverbreak_tripid_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivershift',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='drivershift',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='drivershifttrip',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='drivershifttrip',
            name='startTime',
        ),
        migrations.AddField(
            model_name='drivershift',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivershift',
            name='startDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='startDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 9, 29, 15, 504757, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
