# Generated by Django 4.2.2 on 2024-01-17 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0060_remove_drivershift_endtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverbreak',
            old_name='endDate',
            new_name='endDateTime',
        ),
        migrations.RenameField(
            model_name='driverbreak',
            old_name='startDate',
            new_name='startDateTime',
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 9, 32, 36, 135902, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
