# Generated by Django 4.2.2 on 2024-01-17 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0061_rename_enddate_driverbreak_enddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 10, 9, 48, 205475, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='drivershiftdocket',
            name='standByEndTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drivershiftdocket',
            name='standByStartTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drivershiftdocket',
            name='waitingTimeEnd',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drivershiftdocket',
            name='waitingTimeStart',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
