# Generated by Django 4.2.1 on 2024-01-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0057_alter_driverdocket_shiftdate_alter_rcti_others_and_more'),
        ('Account_app', '0062_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
    ]
