# Generated by Django 4.2.1 on 2024-01-19 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0063_merge_20240118_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 19, 4, 15, 45, 887880, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
