# Generated by Django 4.2.1 on 2024-01-19 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0066_remove_escalation_docketdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationdocket',
            name='invoiceFile',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 19, 5, 17, 43, 375162, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
