# Generated by Django 4.2.2 on 2024-01-19 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0067_escalationdocket_invoicefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 19, 11, 50, 53, 280104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='escalationdocket',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
