# Generated by Django 4.2.1 on 2024-01-19 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0067_escalationdocket_invoicefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 19, 9, 46, 36, 340250, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='escalationType',
            field=models.CharField(default='', max_length=20),
        ),
    ]
