# Generated by Django 4.2.1 on 2024-01-20 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0069_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivershift',
            name='verified',
        ),
        migrations.AddField(
            model_name='drivershifttrip',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 7, 17, 55, 841642, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='escalationType',
            field=models.CharField(default='', max_length=20),
        ),
    ]
