# Generated by Django 4.2.1 on 2024-01-20 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0070_remove_drivershift_verified_drivershifttrip_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershift',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 8, 56, 21, 167259, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
