# Generated by Django 4.2.1 on 2024-01-20 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0071_drivershift_verified_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 9, 8, 38, 608589, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='drivershift',
            name='shiftType',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=200),
        ),
    ]
