# Generated by Django 4.2.1 on 2024-01-20 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0072_alter_driverdocket_shiftdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivershiftdocket',
            name='shiftId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 20, 12, 30, 30, 738197, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
