# Generated by Django 4.2.1 on 2024-01-21 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0074_drivershiftdocket_clientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationreport',
            name='clientId',
        ),
        migrations.AddField(
            model_name='drivershiftdocket',
            name='shiftDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 21, 4, 43, 0, 771654, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
