# Generated by Django 4.2.1 on 2024-01-21 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0075_remove_reconciliationreport_clientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 21, 8, 35, 23, 610333, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='drivershiftdocket',
            unique_together={('docketNumber', 'shiftDate', 'clientId')},
        ),
    ]
