# Generated by Django 4.2.1 on 2024-01-22 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0077_rename_truckid_reconciliationreport_clientid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasttriperror',
            name='exceptionText',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 22, 11, 54, 45, 46673), null=True),
        ),
    ]
