# Generated by Django 4.2.2 on 2024-01-22 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GearBox_app', '0019_alter_clienttruckconnection_startdate_and_more'),
        ('Account_app', '0077_rename_truckid_reconciliationreport_clientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverbreak',
            name='tripId',
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 22, 6, 37, 9, 74475, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='DriverReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiseDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('amount', models.FloatField(default=0)),
                ('reimbursementFile', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('driverId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GearBox_app.driver')),
                ('shiftId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account_app.drivershift')),
            ],
        ),
    ]
