# Generated by Django 4.2.1 on 2024-01-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0078_remove_driverbreak_tripid_and_more'),
        ('Account_app', '0079_alter_drivershiftdocket_unique_together_and_more'),
    ]

    operations = [
    ]
