# Generated by Django 4.2.1 on 2024-01-22 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0080_merge_20240122_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='rctierrors',
            name='exceptionText',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rctierrors',
            name='truckNo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 22, 21, 44, 38, 944813), null=True),
        ),
    ]
