# Generated by Django 4.2.2 on 2024-01-29 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0081_rctierrors_exceptiontext_rctierrors_truckno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 12, 47, 28, 234976, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
