# Generated by Django 4.2.2 on 2024-01-29 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0082_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 12, 48, 17, 421837, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
