# Generated by Django 5.0.1 on 2024-01-31 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0082_drivershift_verifiedby_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 10, 4, 39, 188622, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
