# Generated by Django 5.0.1 on 2024-02-01 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0084_alter_driverdocket_shiftdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 2, 1, 8, 41, 53, 735548, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
